name: CD Pipeline

on:
  push:
    tags:
      - '*'  # Triggers on any tag

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Specify the Java distribution
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Convert Tag and Build Docker Image
        run: |
          # Convert repository owner and tag name to lowercase
          LOWERCASE_REPO=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          TAG_NAME=$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]')

          # Build and tag Docker image
          IMAGE_TAG="ghcr.io/$LOWERCASE_REPO/spring-petclinic:$TAG_NAME"
          docker build -t $IMAGE_TAG .
          docker tag $IMAGE_TAG ghcr.io/$LOWERCASE_REPO/spring-petclinic:latest

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push Docker image to GitHub Container Registry
        run: |
          TAG_NAME=$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]')
          LOWERCASE_REPO=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$LOWERCASE_REPO/spring-petclinic:$TAG_NAME
          docker push ghcr.io/$LOWERCASE_REPO/spring-petclinic:latest
