name: Build and Deploy Spring Petclinic

on:
  push:
    branches:
      - develop
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          LOWERCASE_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          TAG_NAME=$(echo "v1.0.${{ github.run_number }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_TAG="ghcr.io/$LOWERCASE_REPO/spring-petclinic:$TAG_NAME"
          docker build -t $IMAGE_TAG .

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/$LOWERCASE_REPO/spring-petclinic:$TAG_NAME
          docker push ghcr.io/$LOWERCASE_REPO/spring-petclinic:latest
