name: CD Pipeline

on:
  push:
    tags:
      - '*'  # Triggers on any tag

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Specify the Java distribution
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/spring-petclinic:${{ github.ref_name }} .
          docker tag ghcr.io/${{ github.repository_owner }}/spring-petclinic:${{ github.ref_name }} ghcr.io/${{ github.repository_owner }}/spring-petclinic:latest

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/spring-petclinic:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository_owner }}/spring-petclinic:latest
