name: CI/CD Pipeline for Spring Petclinic

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop
      - main

env:
  AWS_REGION: us-east-1 # Replace with your AWS region
  IMAGE_NAME: spring-petclinic

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the application
        run: ./mvnw clean package

      - name: Log in to Amazon ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest ${{ secrets.ECR_REPO_URL }}:latest

      - name: Push to ECR
        run: |
          docker push ${{ secrets.ECR_REPO_URL }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v2
        with:
          version: 'latest'

      - name: Create kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/spring-petclinic spring-petclinic=${{ secrets.ECR_REPO_URL }}:latest
          kubectl rollout status deployment/spring-petclinic
