name: CI for Develop Branch Pull Requests

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }} 

    - name: SSH into EC2 and deploy Docker image
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/authorized_keys ubuntu@${{ secrets.FEATURE_IP }}
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker

          sudo docker pull ghcr.io/eltonebm/spring-petclinic:assa

          sudo docker container run -d --name spring-petclinic -p 8080:8080 ghcr.io/eltonebm/spring-petclinic:assa
