name: CI Pipeline

on:
  push:
    branches:
      - 'feature/*'  # Runs on any feature branch
  pull_request:
    branches:
      - develop  # Runs on pull requests targeting the develop branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Specify the Java distribution
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Verify project is working
        run: mvn verify
