name: CI Pipeline

on:
  push:
    branches:
      - 'feature/*'  # 'feature/' ile başlayan dallarda çalışır
  pull_request:
    branches:
      - '*'  # Herhangi bir dalı hedefleyen çekme isteklerinde çalışır

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları Al
        uses: actions/checkout@v3

      - name: JDK 17 Kur
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: EC2’ye Dağıt
        env:
          FEATURE_IP: ${{ secrets.FEATURE_IP }}  # EC2 IP adresi
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH özel anahtarı
        run: |
          # SSH istemcisini kur
          sudo apt-get update
          sudo apt-get install -y openssh-client

          # SSH anahtar dizinini oluştur ve özel anahtarı ekle
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # EC2'yi bilinen anahtarlar listesine ekle
          ssh-keyscan -H $FEATURE_IP >> ~/.ssh/known_hosts

          # Derlenmiş JAR dosyasını EC2'ye kopyala
          scp -i ~/.ssh/id_rsa target/* ubuntu@$FEATURE_IP:/home/ubuntu/spring-petclinic.jar

          run: ./mvnw package && java -jar target/*.jar
