name: CI Pipeline

on:
  push:
    branches:
      - 'feature/*'  # 'feature/' ile başlayan dallarda çalışır
  pull_request:
    branches:
      - '*'  # Herhangi bir dalı hedefleyen çekme isteklerinde çalışır

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları Al
        uses: actions/checkout@v3

      - name: JDK 17 Kur
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Maven ile Derle
        run: mvn clean install

      - name: Testleri Çalıştır
        run: mvn test

      - name: Projeyi Doğrula
        run: mvn verify

      - name: EC2’ye Dağıt
        env:
          FEATURE_IP: ${{ secrets.FEATURE_IP }}  # EC2 IP adresi
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH özel anahtarı
        run: |
          # SSH istemcisini kur
          sudo apt-get update
          sudo apt-get install -y openssh-client

          # SSH anahtar dizinini oluştur ve özel anahtarı ekle
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # EC2'yi bilinen anahtarlar listesine ekle
          ssh-keyscan -H $FEATURE_IP >> ~/.ssh/known_hosts

          # Derlenmiş JAR dosyasını EC2'ye kopyala
          scp -i ~/.ssh/id_rsa target/spring-petclinic.jar ubuntu@$FEATURE_IP:/home/ubuntu/spring-petclinic.jar

          # EC2 üzerinde uygulamayı yeniden başlat
          ssh -i ~/.ssh/id_rsa ubuntu@$FEATURE_IP << 'EOF'
            # Herhangi bir çalışan uygulamayı durdur (varsa)
            sudo systemctl stop spring-petclinic || true

            # Eski JAR dosyasını yeni dosyayla değiştir
            sudo cp /home/ubuntu/spring-petclinic.jar /opt/spring-petclinic/spring-petclinic.jar

            # Uygulamayı başlat
            sudo systemctl start spring-petclinic

            # Uygulamanın çalıştığını doğrula
            sudo systemctl status spring-petclinic || (echo "Uygulama başlatılamadı" && exit 1)
          EOF

      - name: Dağıtımı Doğrula
        env:
          FEATURE_IP: ${{ secrets.FEATURE_IP }}  # EC2 IP adresi
        run: |
          # Uygulamanın başlama süresi için bekle
          sleep 30

          # Uygulamanın erişilebilir olduğunu kontrol et
          curl -sSf http://$FEATURE_IP:8080 || (echo "Uygulama erişilemez" && exit 1)
