name: Üretime Dağıtım

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Dağıtmak istediğiniz sürüm etiketi'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu Çek
      uses: actions/checkout@v3

    - name: JDK Kurulum
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Sürüm Etiketini Kontrol Et
      id: check_tag
      run: |
        TAG=${{ github.event.inputs.version }}
        echo "Etiket $TAG kontrol ediliyor..."

        # Tüm etiketleri çek
        git fetch --tags

        # Etiketin var olup olmadığını kontrol et
        if git rev-parse "$TAG" >/dev/null 2>&1; then
          echo "Etiket $TAG mevcut."
          echo "version_exists=true" >> $GITHUB_ENV
        else
          echo "Etiket $TAG mevcut değil."
          echo "version_exists=false" >> $GITHUB_ENV
        fi

    - name: SSH ile EC2 Üzerinde Dağıtım
      if: env.version_exists == 'true'
      env:
        MAIN_KEY: ${{ secrets.MAIN_KEY }}
        MAIN_IP: ${{ secrets.MAIN_IP }}
      run: |
        echo "Sürüm ${{ github.event.inputs.version }} üretime dağıtılıyor..."
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/authorized_keys ubuntu@$MAIN_IP << EOF
          # Docker'ın kurulu olup olmadığını kontrol et, yoksa kur
          if ! command -v docker &> /dev/null
          then
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
          fi

          # Önceki container'ı durdur ve kaldır
          docker stop spring-petclinic || true
          docker rm spring-petclinic || true

          # Yeni imajı çek
          sudo docker pull ghcr.io/eltonebm/spring-petclinic:${{ github.event.inputs.version }}

          # Yeni container'ı çalıştır
          sudo docker run -d --name spring-petclinic -p 8080:8080 ghcr.io/eltonebm/spring-petclinic:${{ github.event.inputs.version }}

          echo "Dağıtım başarılı."
        EOF

    - name: Dağıtım Başarısız
      if: env.version_exists == 'false'
      run: |
        echo "Dağıtım başarısız. Etiket ${{ github.event.inputs.version }} mevcut değil."
